from flask import Flask, render_template, jsonify, request
import pandas as pd
import json
import os

app = Flask(__name__)

# --- PATH SETUP ---
# Get the folder where this script lives
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Go up one level and into the 'data' folder
DATA_PATH = os.path.normpath(os.path.join(BASE_DIR, '..', 'data'))

@app.route('/')
def index():
    """Serves the main Spotify-style UI"""
    return render_template('index.html')

@app.route('/api/books')
def get_books():
    """Serves the top-rated engineering books generated by your training script"""
    csv_file = os.path.join(DATA_PATH, 'top_books.csv')
    if os.path.exists(csv_file):
        df = pd.read_csv(csv_file)
        # Ensure we send the data as a list of dictionaries
        return jsonify(df.to_dict('records'))
    else:
        print(f"❌ Error: {csv_file} not found!")
        return jsonify([])

@app.route('/api/recs')
def get_recs():
    """Serves the similarity calculations for the 'Similar Books' tab"""
    json_file = os.path.join(DATA_PATH, 'recs.json')
    if os.path.exists(json_file):
        with open(json_file, 'r', encoding='utf-8') as f:
            return jsonify(json.load(f))
    else:
        print(f"❌ Error: {json_file} not found!")
        return jsonify({})

if __name__ == '__main__':
    print("------------------------------------------")
    print("🚀 Bookify Professional Engine Starting...")
    print(f"📂 Checking data in: {DATA_PATH}")
    print("------------------------------------------")
    # host='0.0.0.0' is REQUIRED for GitHub Codespaces to work
    app.run(host='0.0.0.0', port=8765, debug=True)