from flask import Flask, render_template, jsonify, request
import pandas as pd
import json
import os

app = Flask(__name__)

# --- PATH CONFIGURATION ---
# Get the absolute path of the folder where app.py lives
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Look for the data folder one level up
DATA_PATH = os.path.join(BASE_DIR, '..', 'data')

@app.route('/')
def index():
    """Renders the Spotify-style UI"""
    return render_template('index.html')

@app.route('/api/books')
def get_books():
    """Serves the top-rated books from the CSV generated by train_model.py"""
    csv_file = os.path.join(DATA_PATH, 'top_books.csv')
    if os.path.exists(csv_file):
        df = pd.read_csv(csv_file)
        # We sort by 'score' which was calculated in your train_model.py
        if 'score' in df.columns:
            df = df.sort_values('score', ascending=False)
        return jsonify(df.to_dict('records'))
    return jsonify([])

@app.route('/api/recs')
def get_recs():
    """Serves the pre-calculated similarity dictionary"""
    json_file = os.path.join(DATA_PATH, 'recs.json')
    if os.path.exists(json_file):
        with open(json_file, 'r', encoding='utf-8') as f:
            return jsonify(json.load(f))
    return jsonify({})

if __name__ == '__main__':
    # Using port 8765 to match your project settings
    print("🚀 Bookify Engine starting on http://localhost:8765")
    app.run(host='0.0.0.0', port=8765, debug=True)