from flask import Flask, render_template, jsonify
import pickle
import os
import pandas as pd

app = Flask(__name__)

# Logic to find the data folder
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(BASE_DIR, '..', 'data')

def load_models():
    # We load the files generated by your Notebook/Scripts
    try:
        popular_df = pickle.load(open(os.path.join(DATA_PATH, 'popular.pkl'), 'rb'))
        return popular_df
    except:
        # Fallback if you haven't generated .pkl files yet
        return None

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/books')
def get_books():
    df = load_models()
    if df is not None:
        # Convert your ML dataframe to JSON for the website
        return jsonify(df.to_dict('records'))
    return jsonify([])

if __name__ == '__main__':
    print("🚀 Bookify Server running on http://127.0.0.1:8765")
    app.run(debug=True, port=8765)